[package]
name = "tsm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
serde = "1.0.228"
thiserror = "2.0.17"
toml = "0.9.8"
